"""
This file uses the feather files generated by RRR_analysis.py to visualize results in various ways
"""

import numpy as np
import pandas as pd
import seaborn as sns
from scipy.stats import mannwhitneyu
from itertools import combinations
from matplotlib import pyplot as plt

from analysis_class import FiringRateAnalysis



def extract_brain_regions(brain_regions_compared):
    """Extract individual brain regions from the comparison strings"""
    regions = set()
    for comparison in brain_regions_compared:
        if '_vs_' in comparison:
            reg1, reg2 = comparison.split('_vs_')
            regions.add(reg1)
            regions.add(reg2)
    return sorted(list(regions))


def create_correlation_matrix(rrr_df_resp_range):
    """Create a correlation matrix from the brain region comparison data"""
    # Extract unique brain regions
    unique_regions = extract_brain_regions(rrr_df_resp_range['brain_regions_compared'])
    n_regions = len(unique_regions)

    # Initialize matrix with NaN
    correlation_matrix = np.full((n_regions, n_regions), np.nan)

    # Fill diagonal with 1.0 (perfect self-correlation)
    np.fill_diagonal(correlation_matrix, 1.0)

    # Create region to index mapping
    region_to_idx = {region: idx for idx, region in enumerate(unique_regions)}

    # Fill matrix with mean r² values
    for _, row in rrr_df_resp_range.iterrows():
        comparison = row['brain_regions_compared']
        r2_value = row['r2']

        if '_vs_' in comparison:
            reg1, reg2 = comparison.split('_vs_')
            idx1, idx2 = region_to_idx[reg1], region_to_idx[reg2]

            # Handle both directions (symmetric matrix)
            if np.isnan(correlation_matrix[idx1, idx2]):
                correlation_matrix[idx1, idx2] = r2_value
                correlation_matrix[idx2, idx1] = r2_value
            else:
                # Take mean if multiple values exist
                correlation_matrix[idx1, idx2] = np.mean([correlation_matrix[idx1, idx2], r2_value])
                correlation_matrix[idx2, idx1] = correlation_matrix[idx1, idx2]

    return correlation_matrix, unique_regions


def perform_statistical_tests(rrr_df_resp_range):
    """
    Perform Mann-Whitney U tests between all pairs of brain region comparisons
    with Bonferroni correction
    """
    # Get unique brain region comparisons
    unique_comparisons = rrr_df_resp_range['brain_regions_compared'].unique()

    # Only proceed if we have more than one comparison
    if len(unique_comparisons) < 2:
        return pd.DataFrame()

    # Create all pairwise combinations
    comparison_pairs = list(combinations(unique_comparisons, 2))
    n_comparisons = len(comparison_pairs)

    # Store results
    statistical_results = []

    for comp1, comp2 in comparison_pairs:
        # Get r² values for each comparison
        r2_comp1 = rrr_df_resp_range[rrr_df_resp_range['brain_regions_compared'] == comp1]['r2'].values
        r2_comp2 = rrr_df_resp_range[rrr_df_resp_range['brain_regions_compared'] == comp2]['r2'].values

        # Skip if either group is empty
        if len(r2_comp1) == 0 or len(r2_comp2) == 0:
            continue

        # Perform Mann-Whitney U test
        try:
            statistic, p_value = mannwhitneyu(r2_comp1, r2_comp2, alternative='two-sided')

            # Apply Bonferroni correction
            p_value_corrected = min(p_value * n_comparisons, 1.0)

            # Determine significance level
            if p_value_corrected < 0.001:
                significance = '***'
            elif p_value_corrected < 0.01:
                significance = '**'
            elif p_value_corrected < 0.05:
                significance = '*'
            else:
                significance = 'ns'

            statistical_results.append({
                'comparison_1': comp1,
                'comparison_2': comp2,
                'n_samples_1': len(r2_comp1),
                'n_samples_2': len(r2_comp2),
                'mean_r2_1': np.mean(r2_comp1),
                'mean_r2_2': np.mean(r2_comp2),
                'statistic': statistic,
                'p_value_raw': p_value,
                'p_value_corrected': p_value_corrected,
                'significance': significance
            })

        except Exception as e:
            print(f"Error in statistical test for {comp1} vs {comp2}: {e}")
            continue

    return pd.DataFrame(statistical_results)


def plot_correlation_matrix(correlation_matrix, unique_regions, stim_type, resp_range):
    """Plot the correlation matrix as a heatmap"""
    plt.figure(figsize=(10, 8))

    # Create heatmap
    sns.heatmap(correlation_matrix,
                xticklabels=unique_regions,
                yticklabels=unique_regions,
                annot=True,
                fmt='.3f',
                cmap='coolwarm',
                center=0,
                vmin=0, vmax=1,
                square=True)

    plt.title(f'Brain Region Correlation Matrix (r²)\n{stim_type} - {resp_range}')
    plt.xlabel('Brain Regions')
    plt.ylabel('Brain Regions')
    plt.tight_layout()
    return plt.gcf()


def plot_correlation_boxplot(rrr_df_resp_range, stim_type, resp_range, stats_df=None):
    """Create boxplot of r² values by brain region comparison with statistics"""
    plt.figure(figsize=(15, 8))

    # Create boxplot
    ax = sns.boxplot(data=rrr_df_resp_range,
                     x='brain_regions_compared',
                     y='r2')

    # Add individual points
    sns.stripplot(data=rrr_df_resp_range,
                  x='brain_regions_compared',
                  y='r2',
                  size=4, color='black', alpha=0.6, ax=ax)

    # Add statistical annotations if provided
    if stats_df is not None and not stats_df.empty:
        add_statistical_annotations(ax, stats_df, rrr_df_resp_range)

        # Adjust y-axis limits to accommodate annotations
        current_ylim = ax.get_ylim()
        max_y = rrr_df_resp_range['r2'].max()
        n_significant = len(stats_df[stats_df['significance'] != 'ns'])
        if n_significant > 0:
            ax.set_ylim(current_ylim[0], max_y * (1.3 + n_significant * 0.1))

    plt.title(f'r² Distribution by Brain Region Comparison\n{stim_type} - {resp_range}')
    plt.xlabel('Brain Region Comparison')
    plt.ylabel('r² Value')
    plt.xticks(rotation=45, ha='right')
    plt.tight_layout()
    return plt.gcf()


def add_statistical_annotations(ax, stats_df, rrr_df_resp_range):
    """Add significance annotations to boxplot"""
    if stats_df.empty:
        return

    # Get unique comparisons and their positions
    unique_comparisons = rrr_df_resp_range['brain_regions_compared'].unique()
    comparison_positions = {comp: i for i, comp in enumerate(unique_comparisons)}

    # Get the maximum y-value for positioning annotations
    max_y = rrr_df_resp_range['r2'].max()
    y_increment = max_y * 0.1

    # Add significant comparisons as text annotations
    annotation_height = max_y + y_increment


    for _, row in stats_df.iterrows():
        if row['significance'] != 'ns':
            comp1, comp2 = row['comparison_1'], row['comparison_2']

            # Only show if both comparisons exist in current data
            if comp1 in comparison_positions and comp2 in comparison_positions:
                pos1 = comparison_positions[comp1]
                pos2 = comparison_positions[comp2]

                # Draw line between significant comparisons
                ax.plot([pos1, pos2], [annotation_height, annotation_height],
                        'k-', linewidth=1)

                # Add significance marker
                mid_pos = (pos1 + pos2) / 2
                ax.text(mid_pos, annotation_height + y_increment * 0.2,
                        row['significance'], ha='center', va='bottom', fontsize=10)

                annotation_height += y_increment * 0.8


def save_statistical_results(stats_df, stim_type, resp_range, file_path):
    """Save statistical results to CSV file"""
    if not stats_df.empty:
        stats_filename = f"{file_path}/statistical_results_{stim_type}_{resp_range}.csv"
        stats_df.to_csv(stats_filename, index=False)
        print(f"Statistical results saved to {stats_filename}")

        # Print summary of significant results
        significant_results = stats_df[stats_df['significance'] != 'ns']
        if len(significant_results) > 0:
            print(f"Found {len(significant_results)} significant comparisons for {stim_type} - {resp_range}:")
            for _, row in significant_results.iterrows():
                print(f"  {row['comparison_1']} vs {row['comparison_2']}: "
                      f"p = {row['p_value_corrected']:.4f} {row['significance']}")
        else:
            print(f"No significant differences found for {stim_type} - {resp_range}")


response_ranges = ["onset", "sustained", "offset"]
# response_ranges = ["sustained"]
stim_types = ["pureTones", "AM", "naturalSound"]


fr_db = FiringRateAnalysis(db_suffix="coords_updated")
file_path = fr_db.figdata_path
stim_types = fr_db.stim_types

for stim in stim_types:
    rrr_df = pd.read_feather(f"{file_path}/RRR_results_{stim}.feather")
    print(f"Loaded {len(rrr_df)} results for {stim}")

    for respRange in response_ranges:
        rrr_df_resp_range = rrr_df[rrr_df["response_range"] == respRange]
        print(f"Loaded {len(rrr_df_resp_range)} results for {stim} {respRange}")

        if len(rrr_df_resp_range) > 0:
            # Create and plot correlation matrix
            corr_matrix, regions = create_correlation_matrix(rrr_df_resp_range)
            matrix_fig = plot_correlation_matrix(corr_matrix, regions, stim, respRange)

            if len(rrr_df_resp_range) > 0:
                # Perform statistical tests
                print(f"Performing statistical analysis for {stim} - {respRange}...")
                stats_results = perform_statistical_tests(rrr_df_resp_range)

                # Save statistical results
                save_statistical_results(stats_results, stim, respRange, file_path)

                # Create and plot correlation matrix
                corr_matrix, regions = create_correlation_matrix(rrr_df_resp_range)
                matrix_fig = plot_correlation_matrix(corr_matrix, regions, stim, respRange)

                # Save matrix figure
                matrix_fig.savefig(f"{file_path}/RRR_results/correlation_matrix_{stim}_{respRange}.png",
                                   dpi=300, bbox_inches='tight')
                plt.close(matrix_fig)

                # Create and plot boxplot with statistics
                boxplot_fig = plot_correlation_boxplot(rrr_df_resp_range, stim, respRange, stats_results)

                # Save boxplot figure
                boxplot_fig.savefig(f"{file_path}/RRR_results/correlation_boxplot_{stim}_{respRange}.png",
                                    dpi=300, bbox_inches='tight')
                plt.close(boxplot_fig)

                print(f"Created visualizations for {stim} - {respRange}")
